### ISSUE TITLE
Add JQuery to package.json

### ISSUE THREAD

**Issue by duaneleem** [leemtek/antiochtoastmasters.gatsby#32]
We've been having some UI issues related to JQuery. This could be related to adding this to the index.html.

How about we troubleshoot this further? One action we can take is add it as part of the package.json and integrate it directly to Gatsby.

**Comment by gtumbaga** [comment]
Added a pull request for this:

https://github.com/leemtek/antiochtoastmasters.gatsby/pull/33

this is the closest i could get to a 'proper' way to load jQuery.  From everything I've read online, it's not as strait forward as just importing it into html.js, because of the way react or gatsby works.

Also, when running the project in my dev, it seems the functions.js file coming from the cloudfront CDN was also having intermittent loading issues.
